version: '3'
services:
  frontend:
    container_name: tele-bot-api-frontend
    image: giaphuc/tele-bot-api:1.0.0-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    container_name: tele-bot-api-backend
    image: giaphuc/tele-bot-api:1.0.0-backend
    ports:
      - "8000:8000"
    volumes:
      - /path/to/host/directory:/root/Desktop
    environment:
      - PORT='your_port'
      - BOT_TOKEN='your_bot_token'
      - BOT_NAME='your_bot_name'
      - BOT_USERNAME='your_bot_username'
      - MY_CHAT_ID='your_chat_id'
      - MY_USERNAME='your_telegram_username'
      - MONGODB_USERNAME='your_mongodb_username'
      - MONGODB_PASSWORD='your_mongodb_password'
      - MONGODB_URL='your_mongodb_url'